# Generated by Django 5.2 on 2026-01-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='recharge_cbu',
            field=models.CharField(blank=True, help_text='CBU de la cuenta bancaria para recibir transferencias de recarga de saldo', max_length=22, verbose_name='CBU para Recargas'),
        ),
    ]
