# Generated by Django 5.2 on 2026-01-23

from django.db import migrations, models


def set_default_values(apps, schema_editor):
    """Set default CBU and phone number"""
    AppConfig = apps.get_model("appconfig", "AppConfig")
    config = AppConfig.objects.filter(pk=1).first()
    if config:
        config.recharge_cbu = "0440027130000011162460"
        config.support_phone = "5493413646186"
        config.save()


class Migration(migrations.Migration):
    dependencies = [
        ("appconfig", "0002_appconfig_recharge_cbu"),
    ]

    operations = [
        migrations.AddField(
            model_name="appconfig",
            name="support_phone",
            field=models.CharField(
                blank=True,
                help_text="Número de teléfono de WhatsApp para soporte (incluir código de país)",
                max_length=20,
                verbose_name="Teléfono de Soporte",
            ),
        ),
        migrations.RunPython(
            set_default_values, reverse_code=migrations.RunPython.noop
        ),
    ]
