# Generated by Django 5.2 on 2026-02-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconfig', '0003_appconfig_support_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='fuel_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de referencia del combustible.', max_digits=10, null=True, verbose_name='Precio de Combustible de Referencia'),
        ),
    ]
