# Generated by Django 5.2 on 2026-02-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconfig', '0005_set_default_fuel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonificationTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_liters', models.DecimalField(decimal_places=2, help_text='Cantidad mínima de litros para acceder a este tramo.', max_digits=10, verbose_name='Litros mínimos')),
                ('bonus_percent', models.DecimalField(decimal_places=2, help_text='Porcentaje de bonificación aplicado sobre el monto recargado.', max_digits=5, verbose_name='Bonificación (%)')),
                ('color_intensity', models.FloatField(default=1.0, help_text='Valor entre 0 y 1 para degradado visual (1 = más oscuro).', verbose_name='Intensidad de color')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Orden de visualización (menor número = primero).', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Tramo de bonificación',
                'verbose_name_plural': 'Tramos de bonificación',
                'ordering': ['order', 'min_liters'],
            },
        ),
    ]
