# Generated by Django 5.2 on 2025-09-04 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_plates_brand_plates_model_company_companyassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('holder', 'Titular'), ('dependent', 'Adherido')], max_length=20),
        ),
        migrations.AlterField(
            model_name='companyassignment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plates',
            name='plate_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('account_type', 'holder')), fields=('user',), name='one_holder_account_per_user', violation_error_message='Un usuario solo puede tener una única cuenta titular'),
        ),
        migrations.AddConstraint(
            model_name='dependents',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('holder_account', 'dependent_account'), name='unique_active_dependent_per_holder', violation_error_message='La cuenta adherida ya está asociada a la cuenta titular'),
        ),
        migrations.AddConstraint(
            model_name='plates',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('plate_number', 'holder_account'), name='unique_active_plate_per_holder', violation_error_message='Ya existe una patente activa con este número para esta cuenta titular'),
        ),
    ]
