# Generated by Django 5.2 on 2025-09-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_authorizedplate_holder_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependents',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
