# Generated by Django 5.2 on 2025-09-29 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_dependents_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependents',
            name='status',
        ),
        migrations.CreateModel(
            name='DependentInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('dependent_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='accounts.account')),
                ('holder_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='accounts.account')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('holder_account', 'dependent_account'), name='unique_pending_invitation', violation_error_message='Ya existe una invitación pendiente entre estas cuentas')],
            },
        ),
    ]
