# Generated by Django 5.2 on 2025-10-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_dependents_status_dependentinvitation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dependentinvitation',
            name='unique_pending_invitation',
        ),
        migrations.RemoveField(
            model_name='dependentinvitation',
            name='dependent_account',
        ),
        migrations.AddField(
            model_name='dependentinvitation',
            name='dependent_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddConstraint(
            model_name='dependentinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('holder_account', 'dependent_email'), name='unique_pending_invitation', violation_error_message='Ya existe una invitación pendiente para este correo electrónico'),
        ),
    ]
