# Generated by Django 5.2 on 2025-10-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_dependentinvitation_unique_pending_invitation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created_at']},
        ),
    ]
