# Generated by Django 5.2 on 2025-12-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plates',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('plate_number',), name='unique_active_plate_globally', violation_error_message='Ya existe una patente activa con este número en el sistema'),
        ),
    ]
