# Generated by Django 5.2 on 2026-01-15 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_account_deactivated_at_account_deactivated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='one_holder_account_per_user',
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('account_type', 'holder'), ('is_active', True)), fields=('user',), name='one_holder_account_per_user', violation_error_message='Un usuario solo puede tener una única cuenta titular activa'),
        ),
    ]
