# Generated by Django 5.2 on 2026-05-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_account_balance'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plates',
            name='unique_active_plate_globally',
        ),
    ]
