# Generated by Django 5.2 on 2026-03-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_organism_alter_company_options_plates_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='special',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='unlimited_balance',
            field=models.BooleanField(default=False),
        ),
    ]
