# Generated by Django 5.2 on 2026-03-30 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_initial_organism'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('special', models.CharField(blank=True, help_text='Si tiene valor, la cuenta adherente creada también será special', max_length=50, null=True)),
                ('unlimited_balance', models.BooleanField(default=False, help_text='Si es True, la cuenta adherente creada tendrá saldo ilimitado')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_emails', to='accounts.company')),
                ('dependent_of', models.ForeignKey(help_text='Cuenta titular a la que se asociará el adherente', on_delete=django.db.models.deletion.CASCADE, related_name='authorized_emails', to='accounts.account')),
                ('organism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_emails', to='accounts.organism')),
            ],
            options={
                'verbose_name': 'Email autorizado',
                'verbose_name_plural': 'Emails autorizados',
                'ordering': ['-invited_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('email', 'dependent_of'), name='unique_pending_authorized_email', violation_error_message='Ya existe una invitación pendiente para este email en esta cuenta')],
            },
        ),
    ]
