# Generated by Django 5.2 on 2026-04-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_authorizedemail'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='authorizedemail',
            name='unique_pending_authorized_email',
        ),
        migrations.AddConstraint(
            model_name='authorizedemail',
            constraint=models.UniqueConstraint(fields=('email', 'dependent_of', 'status'), name='unique_authorized_email_per_status', violation_error_message='Ya existe una invitación pendiente para este mail'),
        ),
    ]
