# Generated by Django 5.2 on 2026-04-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_authorizedemail_unique_authorized_email_per_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='display_type',
            field=models.CharField(choices=[('pesos', 'Pesos'), ('litros', 'Litros')], default='pesos', help_text='Determina cómo se muestra el saldo y los movimientos: en pesos o en litros', max_length=20),
        ),
        migrations.AddField(
            model_name='authorizedemail',
            name='display_type',
            field=models.CharField(choices=[('pesos', 'Pesos'), ('litros', 'Litros')], default='pesos', help_text='Tipo de visualización para la cuenta adherente creada (pesos o litros)', max_length=20),
        ),
    ]
