# Generated by Django 5.2 on 2026-04-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_account_display_type_authorizedemail_display_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='tax_condition',
            field=models.CharField(choices=[('responsable_inscripto', 'Responsable Inscripto'), ('exento', 'Exento')], default='responsable_inscripto', help_text='Condición fiscal del organismo frente al IVA', max_length=30, verbose_name='Condición ante IVA'),
        ),
    ]
