# Generated by Django 5.2 on 2026-04-10 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_organism_tax_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece esta cuenta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.company'),
        ),
    ]
