# Generated by Django 5.2 on 2026-04-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_account_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='billing_type',
            field=models.CharField(blank=True, choices=[('invoice', 'Facturación'), ('prepaid', 'Prepago')], max_length=20, null=True, verbose_name='Tipo de facturación'),
        ),
        migrations.AddField(
            model_name='company',
            name='cuit',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='CUIT'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_condition',
            field=models.CharField(blank=True, choices=[('responsable_inscripto', 'Responsable Inscripto'), ('exento', 'Exento')], help_text='Condición fiscal de la empresa frente al IVA', max_length=30, null=True, verbose_name='Condición ante IVA'),
        ),
    ]
