# Generated by Django 5.2 on 2026-05-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_add_billing_fields_to_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedemail',
            name='pending_plates',
            field=models.ManyToManyField(blank=True, help_text='Patentes a asignar automáticamente cuando el usuario se registre', related_name='pending_authorized_emails', to='accounts.plates'),
        ),
    ]
