# Generated by Django 5.2 on 2026-05-29 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_unique_active_plate_globally'),
        ('accounts', '0025_authorizedemail_pending_plates'),
    ]

    operations = [
    ]
