# Generated by Django 5.2 on 2026-05-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_merge_20260529_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='billing_type',
            field=models.CharField(blank=True, choices=[('invoice', 'Postpago'), ('prepaid', 'Prepago')], max_length=20, null=True, verbose_name='Tipo de facturación'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='billing_type',
            field=models.CharField(choices=[('invoice', 'Postpago'), ('prepaid', 'Prepago')], max_length=20),
        ),
    ]
