# Generated by Django 5.2 on 2026-06-05 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_company_billing_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active', 'id'], name='accounts_ac_is_acti_dde80e_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'is_active'], name='accounts_ac_user_id_0bca0f_idx'),
        ),
        migrations.AddIndex(
            model_name='dependents',
            index=models.Index(fields=['holder_account', 'end_date'], name='accounts_de_holder__eb4e27_idx'),
        ),
        migrations.AddIndex(
            model_name='plates',
            index=models.Index(fields=['holder_account', 'end_date'], name='accounts_pl_holder__ed83f3_idx'),
        ),
    ]
