# Generated by Django 5.2 on 2026-07-31 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_account_accounts_ac_is_acti_dde80e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dependentinvitation',
            name='dependent_user',
            field=models.ForeignKey(blank=True, help_text='Usuario destinatario de la invitación, si ya está registrado. No reemplaza a dependent_email todavía: se irá poblando en una etapa posterior.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
