# Generated by Django 5.2 on 2026-01-05 16:36

from django.db import migrations


from django.utils import timezone
from datetime import timedelta

def create_wicored_promo(apps, schema_editor):
    PromotionCode = apps.get_model('promotions', 'PromotionCode')
    if not PromotionCode.objects.filter(code='WICORED').exists():
        PromotionCode.objects.create(
            code='WICORED',
            description='Código de bienvenida para crear cuenta titular',
            action_type='CREATE_HOLDER_ACCOUNT',
            active=True,
            valid_from=timezone.now(),
            valid_to=timezone.now() + timedelta(days=365)
        )

def remove_wicored_promo(apps, schema_editor):
    PromotionCode = apps.get_model('promotions', 'PromotionCode')
    PromotionCode.objects.filter(code='WICORED').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_wicored_promo, remove_wicored_promo),
    ]
