# Generated by Django 5.2 on 2026-01-08 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_create_wicored_promo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='promotionredemption',
            name='unique_user_code_redemption',
        ),
        migrations.AddField(
            model_name='promotioncode',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Número máximo de veces que puede ser canjeado (vacío = ilimitado)', null=True),
        ),
        migrations.AddField(
            model_name='promotionredemption',
            name='amount_gifted',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Saldo regalado (si aplica)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='action_type',
            field=models.CharField(choices=[('CREATE_HOLDER_ACCOUNT', 'Crear Cuenta Titular'), ('GIFT_BALANCE', 'Regalar Saldo')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='promotionredemption',
            index=models.Index(fields=['user', 'promotion_code'], name='promotions__user_id_443423_idx'),
        ),
    ]
