# Generated by Django 5.2 on 2026-01-08 15:00

from django.db import migrations


def create_gift_balance_promo(apps, schema_editor):
    """
    Crea un código promocional de regalo de $15,000 pesos
    """
    PromotionCode = apps.get_model("promotions", "PromotionCode")

    # Crear código de regalo de $15,000 con 10 usos
    PromotionCode.objects.get_or_create(
        code="PUMAS",
        defaults={
            "description": "Código promocional de bienvenida - Regalo de $15,000 pesos de saldo",
            "active": True,
            "action_type": "GIFT_BALANCE",
            "action_params": {"amount": 15000},
            "max_uses": 10,  # Configurable: límite de 10 usos
        },
    )


def reverse_gift_balance_promo(apps, schema_editor):
    """
    Elimina el código promocional de regalo
    """
    PromotionCode = apps.get_model("promotions", "PromotionCode")
    PromotionCode.objects.filter(code="REGALO15K").delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "promotions",
            "0003_remove_promotionredemption_unique_user_code_redemption_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(create_gift_balance_promo, reverse_gift_balance_promo),
    ]
