# Generated by Django 5.2 on 2026-01-08 16:00

from django.db import migrations


def deactivate_pumas_code(apps, schema_editor):
    """
    Desactiva el código promocional PUMAS
    """
    PromotionCode = apps.get_model("promotions", "PromotionCode")
    PromotionCode.objects.filter(code="PUMAS").update(active=False)


def reactivate_pumas_code(apps, schema_editor):
    """
    Reactiva el código promocional PUMAS (reverse migration)
    """
    PromotionCode = apps.get_model("promotions", "PromotionCode")
    PromotionCode.objects.filter(code="PUMAS").update(active=True)


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0004_create_gift_balance_promo"),
    ]

    operations = [
        migrations.RunPython(deactivate_pumas_code, reactivate_pumas_code),
    ]
