# Generated by Django 5.2 on 2026-01-22 14:03

import django.core.validators
import django.db.models.deletion
import promotions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_deactivate_pumas_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo de la imagen promocional', max_length=200)),
                ('image', models.ImageField(help_text='Imagen promocional (JPG, PNG, WebP - Max 5MB)', upload_to='promotional_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Solo se permiten archivos JPG, PNG o WebP'), promotions.models.validate_image_size])),
                ('is_active', models.BooleanField(default=True, help_text='Si está activa, se mostrará en la app')),
                ('order', models.IntegerField(default=0, help_text='Orden de aparición (menor número = aparece primero)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó esta imagen promocional', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotional_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagen Promocional',
                'verbose_name_plural': 'Imágenes Promocionales',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='promotions__is_acti_3ca37d_idx')],
            },
        ),
    ]
