# Generated by Django 5.2 on 2025-10-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_rolassignment_role_remove_rolassignment_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
