# Generated by Django 5.2 on 2026-07-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_create_transporte_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
