# Generated by Django 5.2 on 2025-10-09 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_remove_dependentinvitation_unique_pending_invitation_and_more'),
        ('stations', '0004_rename_latitude_station_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FuelLoadOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('no_balance', 'Sin saldo'), ('canceled', 'Cancelada'), ('timed_out', 'Expirada')], default='pending', max_length=20)),
                ('timestamp_started', models.DateTimeField(auto_now_add=True)),
                ('timestamp_atended', models.DateTimeField(blank=True, null=True)),
                ('timestamp_finished', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_operations', to='accounts.account')),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attended_operations', to=settings.AUTH_USER_MODEL)),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.plates')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operation.paymentmethod')),
            ],
            options={
                'ordering': ('-timestamp_started',),
            },
        ),
    ]
