# Generated by Django 5.2 on 2025-10-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_alter_fuelloadoperation_attendant'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelloadoperation',
            name='fill_full_tank',
            field=models.BooleanField(default=False),
        ),
    ]
