# Generated by Django 5.2 on 2025-10-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_fuelloadoperation_fill_full_tank'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelloadoperation',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuelloadoperation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('no_balance', 'Sin saldo'), ('canceled', 'Cancelada'), ('timed_out', 'Expirada'), ('waiting_canceled', 'Espera cancelada'), ('canceled_by_attendee', 'Cancelada por el playero'), ('canceled_by_user', 'Cancelada por el usuario')], default='pending', max_length=20),
        ),
    ]
