# Generated by Django 5.2 on 2025-11-03 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_options'),
        ('operation', '0005_fuelloadoperation_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelloadoperation',
            name='plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.plates'),
        ),
    ]
