# Generated by Django 5.2 on 2025-11-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_alter_fuelloadoperation_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelloadoperation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('no_balance', 'Sin saldo'), ('canceled', 'Cancelada'), ('timed_out', 'Expirada'), ('waiting_canceled', 'Espera cancelada por el usuario'), ('canceled_by_attendee', 'Cancelada por el playero'), ('canceled_by_user', 'Cancelada por el usuario')], default='pending', max_length=20),
        ),
    ]
