# Generated by Django 5.2 on 2025-12-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_transfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ('-timestamp',)},
        ),
    ]
