# Generated by Django 5.2 on 2025-12-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_modifyfunds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifyfunds',
            name='reason',
        ),
    ]
