# Generated by Django 5.2 on 2026-01-21 16:28

import django.core.validators
import django.db.models.deletion
import operation.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_account_one_holder_account_per_user_and_more'),
        ('operation', '0012_remove_modifyfunds_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceRechargeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be added to the account', max_digits=12)),
                ('transfer_proof', models.FileField(help_text='Proof of bank transfer (PDF, JPG, PNG - Max 5MB)', upload_to='recharge_proofs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Solo se permiten archivos PDF, JPG o PNG'), operation.models.validate_file_size])),
                ('comments', models.TextField(blank=True, help_text='Optional comments from the user')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the request was reviewed', null=True)),
                ('review_comments', models.TextField(blank=True, help_text='Comments from the reviewer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='Account to be recharged', on_delete=django.db.models.deletion.CASCADE, related_name='recharge_requests', to='accounts.account')),
                ('requested_by', models.ForeignKey(help_text='User who requested the recharge', on_delete=django.db.models.deletion.CASCADE, related_name='recharge_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Gestor/Admin who reviewed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_recharge_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Recarga',
                'verbose_name_plural': 'Solicitudes de Recarga',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at'], name='operation_b_created_402eed_idx'), models.Index(fields=['status', '-created_at'], name='operation_b_status_8626b8_idx')],
            },
        ),
    ]
