# Generated by Django 5.2 on 2026-02-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0013_balancerechargerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancerechargerequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount to be added to the account', max_digits=15),
        ),
        migrations.AlterField(
            model_name='fuelloadoperation',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='fuelloadoperation',
            name='initial_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='modifyfunds',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
