# Generated by Django 5.2 on 2026-03-30 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0014_alter_balancerechargerequest_amount_and_more'),
        ('stations', '0008_fueltype_fueltypeprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelloadoperation',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_operations', to='stations.fueltype'),
        ),
        migrations.AddField(
            model_name='fuelloadoperation',
            name='odometer_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelloadoperation',
            name='quantity_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
