# Generated by Django 5.2 on 2026-03-30 17:27

from django.db import migrations


def update_fk_constraint(apps, schema_editor):
    """Update FK on fuel_type_id to point to stations_fueltype
    and drop old operation_fueltype* tables."""
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        # Find and drop the old FK constraint referencing operation_fueltype
        cursor.execute("""
            SELECT tc.constraint_name
            FROM information_schema.table_constraints tc
            JOIN information_schema.constraint_column_usage ccu
              ON tc.constraint_name = ccu.constraint_name
              AND tc.constraint_schema = ccu.constraint_schema
            WHERE tc.table_name = 'operation_fuelloadoperation'
              AND tc.constraint_type = 'FOREIGN KEY'
              AND ccu.table_name = 'operation_fueltype'
              AND ccu.column_name = 'id';
        """)
        rows = cursor.fetchall()
        for (constraint_name,) in rows:
            cursor.execute(
                f'ALTER TABLE operation_fuelloadoperation DROP CONSTRAINT "{constraint_name}";'
            )

        # Add new FK constraint pointing to stations_fueltype
        cursor.execute("""
            ALTER TABLE operation_fuelloadoperation
            ADD CONSTRAINT operation_fuelloadop_fuel_type_id_stations_fk
            FOREIGN KEY (fuel_type_id) REFERENCES stations_fueltype(id)
            DEFERRABLE INITIALLY DEFERRED;
        """)

        # Drop old tables (FuelTypePrice first due to FK)
        cursor.execute("DROP TABLE IF EXISTS operation_fueltypeprice CASCADE;")
        cursor.execute("DROP TABLE IF EXISTS operation_fueltype CASCADE;")


class Migration(migrations.Migration):
    dependencies = [
        ("operation", "0015_fuelloadoperation_fuel_type_and_more"),
        ("stations", "0008_fueltype_fueltypeprice"),
    ]

    operations = [
        migrations.RunPython(update_fk_constraint, migrations.RunPython.noop),
    ]
