# Generated by Django 5.2 on 2026-06-05 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_account_accounts_ac_is_acti_dde80e_idx_and_more'),
        ('operation', '0017_fuelloadoperation_co2_saved_kg'),
        ('stations', '0013_add_new_stations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fuelloadoperation',
            index=models.Index(fields=['status', '-timestamp_started'], name='operation_f_status_d5e10a_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelloadoperation',
            index=models.Index(fields=['station', '-timestamp_started'], name='operation_f_station_7d2998_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelloadoperation',
            index=models.Index(fields=['account', '-timestamp_started'], name='operation_f_account_a48458_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelloadoperation',
            index=models.Index(fields=['attendant', '-timestamp_started'], name='operation_f_attenda_8652dc_idx'),
        ),
        migrations.AddIndex(
            model_name='modifyfunds',
            index=models.Index(fields=['account', '-timestamp'], name='operation_m_account_7212dd_idx'),
        ),
    ]
