# Generated by Django 5.2 on 2026-07-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0018_fuelloadoperation_operation_f_status_d5e10a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancerechargerequest',
            name='transfer_origin_name',
            field=models.CharField(blank=True, help_text='Name of the bank account holder when the transfer comes from a third party', max_length=255),
        ),
    ]
