# Generated by Django 5.2 on 2025-09-02 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_type', models.CharField(choices=[('holder', 'Holder'), ('dependent', 'Dependent')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dependents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('dependent_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents_as_dependent', to='accounts.account')),
                ('holder_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents_as_holder', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Plates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=10, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('holder_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizedPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('dependent_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_plate_dependent', to='accounts.account')),
                ('holder_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_plate_holder', to='accounts.account')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.plates')),
            ],
        ),
    ]
