# Generated by Django 5.2 on 2025-09-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_account_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizedplate',
            name='holder_account',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='authorizedplate',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('plate', 'dependent_account'), name='unique_active_authorized_plate', violation_error_message='Ya existe una autorización activa con esta patente para esta cuenta'),
        ),
    ]
