### POST Requesting a token ADMIN
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
content-type: application/json

{
    "email": "playero@example.com", 
    "password": "ADSqew132"
}

### POST Requesting a token ADMIN
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
content-type: application/json

{
    "email": "playero@example.com", 
    "password": "ADSqew132"
}
###

# Pruebas usuarios

POST http://back-appmobile-tst.wico.com.ar:5000/users/ HTTP/1.1
content-type: application/json

{
    "email": "carlos.perez@example.com",
    "dni": "42326218",
    "first_name": "Carlos",
    "last_name": "Perez",
    "phone_number": "123456789",
    "password": "asdasdasd"
}

### --- USUARIOS ---
### POST registering user
POST http://127.0.0.1:8000/users/ HTTP/1.1
content-type: application/json

{
    "email": "carlos.perez@example.com",
    "dni": "42326218",
    "first_name": "Carlos",
    "last_name": "Perez",
    "phone_number": "123456789",
    "password": "asdasdasd"
}

### POST Requesting a token ADMIN
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
content-type: application/json

{
    "email": "admin@example.com", 
    "password": "asdasdasd"}

### POST Requesting a token GESTOR
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
content-type: application/json

{
    "email": "gestor2@example.com", 
    "password": "asdasdasd"}

### POST Token refresh
POST http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
content-type: application/json

{"refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NDc1ODM5MiwiaWF0IjoxNzQ0NjcxOTkyLCJqdGkiOiJhZWY1Njc1ZDdmOGE0OGE1YTAyNjg1YTQ3MmYxMWEzZSIsInVzZXJfaWQiOjR9.D9ZSGXlBEzjkLZDoWP6VumXTfYoTC_5hb9qf1irDdfg"}

### GET user list
GET http://127.0.0.1:8000/users/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MTk3NzAxLCJpYXQiOjE3NTUxOTQxMDEsImp0aSI6ImIzYmU3MmMyNGY1ZjQwNTNhMGU0YmM2ODlkNjg5ZTU2IiwidXNlcl9pZCI6OX0.ZKY23RTKsS0WhNJs24-ekmLzdS7XkJhPQrB9V_qE99w

### GET my user
GET http://127.0.0.1:8000/users/me/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2OTEzNTc1LCJpYXQiOjE3NTY5MDk5NzUsImp0aSI6IjExM2FhMmMzODI1NDQwZDdiZTc2Mjc2ODc0NDEwNDY4IiwidXNlcl9pZCI6MTh9.5BszEjU9H4U1esJH84IyNolJR1Ck1uO2lz-miwR7DTU

### LOCATIONS ###

### GET countries list
GET http://127.0.0.1:8000/locations/countries/ HTTP/1.1

### GET list of cities of province with id 20
GET http://127.0.0.1:8000/locations/cities/?province_id=20 HTTP/1.1

### POST create a new country
POST http://127.0.0.1:8000/locations/countries/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2OTIxNDg1LCJpYXQiOjE3NTY5MTc4ODUsImp0aSI6IjYyOTZmYWI5NWM4MjQzMDBiYjU1NzRlOGZjNjJmMjYxIiwidXNlcl9pZCI6MTh9.yercls5qR1_Qe8oHcjOig1TFUHeZHl6UIiond4gMB_8

{
    "name": "Uruguay"
}


### ACCOUNTS ###

### GET all accounts
GET http://127.0.0.1:8000/accounts/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2ODI3MjgyLCJpYXQiOjE3NTY4MjM2ODIsImp0aSI6ImFkMGRjZDBiNDdiNDRlZTJiNGVmNDI1ZTAxNTRhMjkyIiwidXNlcl9pZCI6OX0.vPhTJeAve62LaF1dDZumuZDK5kylr66Z93-cyz6cvag



### GET account by id
GET http://127.0.0.1:8000/accounts/accounts/1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2ODI3MjgyLCJpYXQiOjE3NTY4MjM2ODIsImp0aSI6ImFkMGRjZDBiNDdiNDRlZTJiNGVmNDI1ZTAxNTRhMjkyIiwidXNlcl9pZCI6OX0.vPhTJeAve62LaF1dDZumuZDK5kylr66Z93-cyz6cvag


### POST create account
POST http://127.0.0.1:8000/accounts/accounts/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2ODI3MjgyLCJpYXQiOjE3NTY4MjM2ODIsImp0aSI6ImFkMGRjZDBiNDdiNDRlZTJiNGVmNDI1ZTAxNTRhMjkyIiwidXNlcl9pZCI6OX0.vPhTJeAve62LaF1dDZumuZDK5kylr66Z93-cyz6cvag

{
    "user": 2,
    "balance": "0",
    "account_type": "dependent"
}

### DEPENDENTS ###

### GET all dependents
GET http://127.0.0.1:8000/accounts/dependents/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2ODI3MjgyLCJpYXQiOjE3NTY4MjM2ODIsImp0aSI6ImFkMGRjZDBiNDdiNDRlZTJiNGVmNDI1ZTAxNTRhMjkyIiwidXNlcl9pZCI6OX0.vPhTJeAve62LaF1dDZumuZDK5kylr66Z93-cyz6cvag


### POST create dependent
POST http://127.0.0.1:8000/accounts/dependents/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2ODI3MjgyLCJpYXQiOjE3NTY4MjM2ODIsImp0aSI6ImFkMGRjZDBiNDdiNDRlZTJiNGVmNDI1ZTAxNTRhMjkyIiwidXNlcl9pZCI6OX0.vPhTJeAve62LaF1dDZumuZDK5kylr66Z93-cyz6cvag

{
    "holder_account": 1,
    "dependent_account": 2,
    "start_date": "2025-09-02"
}


### PLATES ###

### GET all plates
GET http://127.0.0.1:8000/accounts/plates/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2ODI3MjgyLCJpYXQiOjE3NTY4MjM2ODIsImp0aSI6ImFkMGRjZDBiNDdiNDRlZTJiNGVmNDI1ZTAxNTRhMjkyIiwidXNlcl9pZCI6OX0.vPhTJeAve62LaF1dDZumuZDK5kylr66Z93-cyz6cvag


### POST create plate
POST http://127.0.0.1:8000/accounts/plates/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2ODI3MjgyLCJpYXQiOjE3NTY4MjM2ODIsImp0aSI6ImFkMGRjZDBiNDdiNDRlZTJiNGVmNDI1ZTAxNTRhMjkyIiwidXNlcl9pZCI6OX0.vPhTJeAve62LaF1dDZumuZDK5kylr66Z93-cyz6cvag

{
    "plate_number": "ABC123",
    "holder_account": 1,
    "start_date": "2025-09-02"
}

### AUTHORIZED PLATES ###

### GET all authorized plates
GET http://127.0.0.1:8000/accounts/authorized-plates/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2ODI3MjgyLCJpYXQiOjE3NTY4MjM2ODIsImp0aSI6ImFkMGRjZDBiNDdiNDRlZTJiNGVmNDI1ZTAxNTRhMjkyIiwidXNlcl9pZCI6OX0.vPhTJeAve62LaF1dDZumuZDK5kylr66Z93-cyz6cvag

### POST create authorized plate
POST http://127.0.0.1:8000/accounts/authorized-plates/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2ODI3MjgyLCJpYXQiOjE3NTY4MjM2ODIsImp0aSI6ImFkMGRjZDBiNDdiNDRlZTJiNGVmNDI1ZTAxNTRhMjkyIiwidXNlcl9pZCI6OX0.vPhTJeAve62LaF1dDZumuZDK5kylr66Z93-cyz6cvag

{
    "holder_account": 1,
    "dependent_account": 7,
    "plate": 1,
    "start_date": "2025-09-02"
}
### OPERATIONS ###

GET http://127.0.0.1:8000/operations/fuel-load-operations?status=completed HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwMDIxMDAzLCJpYXQiOjE3NjAwMTM4MDMsImp0aSI6IjQyZDc3NDIyMjgwZTQ5ZDRiNGU1NDkyY2M4MTAwMDdiIiwidXNlcl9pZCI6MX0.0Yzw-JoDbfTUCMAjmnE6ToKzCXA5Vsr0vyjuLTmsrkQ

