[pytest]
DJANGO_SETTINGS_MODULE = myapp.settings.test
python_files = tests.py test_*.py *_test.py
filterwarnings =
    ignore:Converter 'drf_format_suffix' is already registered.*:django.utils.deprecation.RemovedInDjango60Warning
    ignore:ast.NameConstant is deprecated.*:DeprecationWarning:reportlab
