# Generated by Django 5.2 on 2025-09-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_id_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolassignment',
            name='role',
        ),
        migrations.RemoveField(
            model_name='rolassignment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='RolAssignment',
        ),
    ]
