# Generated by Django 5.2 on 2025-09-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_country_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='postal_code',
        ),
    ]
