# Generated by Django 5.2 on 2025-10-14 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('login', 'Inicio de sesión'), ('balance', 'Saldo y pagos'), ('fuel_load', 'Carga de combustible'), ('transactions', 'Movimientos'), ('other', 'Otro problema')], help_text='Categoría del error reportado', max_length=20)),
                ('description', models.TextField(help_text='Descripción detallada del problema', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('resolved', 'Resuelto'), ('closed', 'Cerrado')], default='pending', help_text='Estado del reporte', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Usuario que reporta el error', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de error',
                'verbose_name_plural': 'Reportes de errores',
                'ordering': ['-created_at'],
            },
        ),
    ]
