# Generated by Django 5.2 on 2025-10-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorreport',
            options={'ordering': ['-created_at']},
        ),
    ]
