# Generated by Django 5.2 on 2025-12-11 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_errorreport_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Número de teléfono de contacto', max_length=20)),
                ('contact_time', models.CharField(help_text='Horario preferido de contacto', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('contacted', 'Contactado'), ('converted', 'Convertido'), ('rejected', 'Rechazado')], default='pending', help_text='Estado de la solicitud', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas internas del gestor', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Usuario que solicita contacto', on_delete=django.db.models.deletion.CASCADE, related_name='fleet_contact_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de contacto - Flotas',
                'verbose_name_plural': 'Solicitudes de contacto - Flotas',
                'ordering': ['-created_at'],
            },
        ),
    ]
