# Generated by Django 5.2 on 2025-10-06 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0004_remove_city_postal_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('street_number', models.CharField(max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.province')),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
                'unique_together': {('name', 'street', 'street_number', 'city')},
            },
        ),
        migrations.CreateModel(
            name='StationAttendantAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
            options={
                'verbose_name': 'Station attendant assignment',
                'verbose_name_plural': 'Station attendant assignments',
                'ordering': ('-start_date', 'attendant__id'),
                'constraints': [models.UniqueConstraint(fields=('attendant', 'station', 'start_date'), name='unique_assignment_per_start_date')],
            },
        ),
    ]
