# Generated by Django 5.2 on 2025-10-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_station_latitude_station_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='street_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
