# Generated by Django 5.2 on 2025-10-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_alter_station_street_alter_station_street_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='longitude',
            new_name='lon',
        ),
    ]
