# Generated by Django 5.2 on 2026-01-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_rename_latitude_station_lat_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stationattendantassignment',
            name='unique_assignment_per_start_date',
        ),
    ]
