# Generated by Django 5.2 on 2026-02-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_remove_stationattendantassignment_unique_assignment_per_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
