# Generated by Django 5.2 on 2026-03-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_station_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='expendio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
