# Generated by Django 5.2 on 2026-03-30 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_organism_alter_company_options_plates_year_and_more'),
        ('stations', '0007_station_expendio'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de combustible',
                'verbose_name_plural': 'Tipos de combustible',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FuelTypePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_prices', to='accounts.company')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stations.fueltype')),
            ],
            options={
                'verbose_name': 'Precio de combustible',
                'verbose_name_plural': 'Precios de combustible',
                'ordering': ['-effective_date'],
            },
        ),
    ]
