# Generated by Django 5.2 on 2026-04-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_initial_fuel_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltype',
            name='biofuel_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de biocombustible contenido en este combustible (ej: 7.5 para 7.5%)', max_digits=5, null=True, verbose_name='Porcentaje de biocombustible'),
        ),
    ]
