# Generated by Django 5.2 on 2026-05-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0011_set_biofuel_percentages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='expendio',
            field=models.CharField(blank=True, choices=[('cordoba', 'Exclusiva Biocombustibles Córdoba')], max_length=100, null=True),
        ),
    ]
