# Generated by Django 5.2 on 2026-08-03 17:09
#
# La dimensión "empresa" de FuelTypePrice se reemplaza por "estación".
# No existe un mapeo posible de company -> station para los precios ya
# cargados, así que se los borra antes de quitar el campo `company`.

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def borrar_precios_existentes(apps, schema_editor):
    """Borra los FuelTypePrice existentes: no hay forma de mapear su
    `company` a una `station`."""
    FuelTypePrice = apps.get_model("stations", "FuelTypePrice")
    FuelTypePrice.objects.all().delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0014_add_gnc_fuel_type'),
    ]

    operations = [
        migrations.RunPython(borrar_precios_existentes, noop),
        migrations.AlterModelOptions(
            name='fueltypeprice',
            options={'ordering': ['-effective_date', '-id'], 'verbose_name': 'Precio de combustible', 'verbose_name_plural': 'Precios de combustible'},
        ),
        migrations.RemoveField(
            model_name='fueltypeprice',
            name='company',
        ),
        migrations.AddField(
            model_name='fueltypeprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fueltypeprice',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_prices', to='stations.station'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='fueltypeprice',
            index=models.Index(fields=['station', 'fuel_type', '-effective_date'], name='ftp_station_fuel_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='fueltypeprice',
            constraint=models.UniqueConstraint(fields=('station', 'fuel_type', 'effective_date'), name='uniq_station_fueltype_date'),
        ),
    ]
