name: Deploy Backend

on:
  push:
    branches: [ main , Prod ]

jobs:
  deploy-test:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Test Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/myapp/backend
            git pull origin main
            docker-compose build backend
            docker-compose up -d backend

  deploy-production:
    if: github.ref == 'refs/heads/Prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP_PROD }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY_DOCKER }}
          script: |
            cd /home/ubuntu/myapp/backend
            git pull origin Prod
            docker-compose build
            docker-compose up -d
